theme = "reveal-hugo"
baseURL = "https://strongjz.github.io/k8s-networking"
languageCode = "en-us"
publishDir = "docs"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "moon"
