apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer